<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE partido[
<!ELEMENT partido (fecha,hora,equipos,acciones)>
<!ATTLIST partido xmlns CDATA #REQUIRED xmlns:accion CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT equipos (equipo,equipo)>
<!ELEMENT equipo (jugadores)>
<!ATTLIST equipo equipo ID 	#REQUIRED tipo (L|V) #REQUIRED>
<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador EMPTY>
<!ATTLIST jugador nombre ID #REQUIRED dorsal CDATA #REQUIRED
		posicion (portero|defensa|delantero|centro) #IMPLIED>
<!ELEMENT acciones (accion*)> 
<!ELEMENT accion  (minuto,accion:equipo,accion:jugador)> <!--CONSIDERAMOS QUE PUEDE HABER UN PARTIDO SIN ACCIONES -->
<!ATTLIST accion tipo (Gol|TR|TA|Penalti|FJ) #REQUIRED>
<!ELEMENT minuto (#PCDATA)> 
<!ELEMENT accion:equipo (#PCDATA)>
<!ELEMENT accion:jugador (#PCDATA)> 
]
>
<partido xmlns="www.partidos.es"
			xmlns:accion="www.partidos.es/accion">
	<fecha>2024-01-01</fecha>
	 <hora>17:00</hora>
	 <equipos>
		<equipo tipo="L" equipo ="RM" >
			<jugadores>
				<jugador nombre="Bolignhan" dorsal="5" posicion="centro"/>
				<jugador nombre="Vinicius" dorsal="7" posicion="delantero"/>
			</jugadores>
		</equipo>
		<equipo tipo="V" equipo ="Barcelona" >
			<jugadores>
				<jugador nombre="Gabi" dorsal="6" posicion="centro"/>
				<jugador nombre="Pedri" dorsal="7" posicion="delantero"/>
			</jugadores>
		</equipo>
	 </equipos>
	 <acciones>
		<accion tipo="Gol">
			<minuto>6</minuto>
			<accion:equipo>RM</accion:equipo>
			<accion:jugador>5</accion:jugador>
		</accion>
	 </acciones>
</partido>