<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE agenda[
<!ELEMENT agenda (lista)>  
<!ELEMENT lista (contacto+)>   <!-- +:1..n  (uno o maas)  -->
<!ELEMENT contacto ( nombre, telefonos, email*)>    <!-- *: 0..n (0 o muchos)-->
<!ATTLIST contacto id ID #REQUIRED grupo CDATA #IMPLIED sexo (M|F) #REQUIRED >
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT telefonos (telefono+)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
]
>
<agenda>
	<lista>
		<contacto id="c1" grupo="DAW" sexo="F">
			<nombre>Lubna</nombre>
			<telefonos>
				<telefono>123456789</telefono>
			</telefonos>
			<email>lubna1@gmail.com</email>
		</contacto>
		<contacto id="c2" sexo="F">
			<nombre>Fatima</nombre>
			<telefonos>
				<telefono>79816098</telefono>
			</telefonos>
		</contacto>
		<contacto id="c3"  grupo="DAM" sexo="M">
			<nombre>Carlos</nombre>
			<telefonos>
				<telefono>815498098</telefono>
				<telefono>092792173</telefono>
				<telefono>871987622</telefono>
			</telefonos>
			<email>carlos3@gmail.com</email>
			<email>carlos33@gmail.com</email>
		</contacto>
	</lista>
</agenda>